##########################################################################
# Standard Properties
kotlin.code.style = official
org.gradle.jvmargs = -Xmx2G
org.gradle.warning.mode = all
org.gradle.configuration-cache = false
##########################################################################
# Standard BTA Dependencies
bta_version = 7.3_04
# Options are release, prerelease, nightly, and misc.
bta_channel = release
loader_version = 0.17.3-bta.8
loom_version = 1.13.0-bta
java_version = 8
##########################################################################
# Mod Properties
mod_version = 1.0.0
mod_group = io.github.apollointhehouse
mod_name = LANWorlds
##########################################################################
kotlin_version = 2.2.21
fabric_language_kotlin_version = 1.13.7+kotlin.2.2.21
##########################################################################
# Mod Dependencies
mod_menu_version = 3.0.0
halplibe_version = 5.3.1
legacy_lwjgl_version = 1.0.6
##########################################################################
# 3rd Party Dependencies
slf4j_api_version = 2.0.17
log4j_version = 2.20.0
guava_version = 33.5.0-jre
gson_version = 2.13.2
commons_lang3_version = 3.19.0
lwjgl_version = 3.3.3
##########################################################################
# Plugin Dependency
foojay_resolver_version = 1.0.0
##########################################################################
